<?php
return [
    'gender' => 'man',
    'cloth' => '
        wszystkie,
        płaszcze,
        bluzy i swetry,
        kurtki zimowe,
        jeansy,
        koszulki,
        marynarki,
        koszule,
        spodnie,
        garnitury,
        bielizna',
    'value_cloth' => '
        coats,
        sweatshirts_and_sweaters,
        winter_coats,
        jeans,
        T-shirts,
        navy,
        shirts,
        trousers,
        suits,
        underwear',

    'shoes' => '
        wszystkie,
        buty zimowe,
        obuwie sznurowane,
        trampki i sneakersy,
        półbuty,
        oksfordy,
        mokasyny,
        botki,
        obuwie biznesowe,
        obuwie sportowe,
        obuwie outdoor',
    'value_shoes' => '
        winter_boots,
        lace-up_shoes,
        sneakers_and_sneakers,
        shoes,
        oksfordy,
        moccasins,
        boots,
        business_footwear,
        sports_shoes,
        outdoor_footwear',
];
