<?php

return [
    'gender' => 'woman',
    'cloth' => '
        wszystkie,
        płaszcze,
        swetry i bluzy,
        kurtki i marynarki,
        sukienki,
        koszulki i topy,
        bluzki i koszule,
        jeansy,
        spodnie,
        spódnice,
        bielizna',
    'value_cloth' => '
        ,
        coats,
        sweaters_and_sweatshirts,
        jackets_and_blazers,
        dresses,
        shirts_and_tops,
        blouses_and_shirts,
        jeans,
        pants,
        skirts,
        underwear',

    'shoes' => '
        wszystkie,
        trampki i sneakersy,
        botki,
        półbuty,
        kozaki,
        czółenka,
        szpilki,
        baleriny,
        obuwie sportowe,
        obuwie wegańskie,
        na szeroką stopę',
    'value_shoes' => '
        ,
        sneakers_and_sneakers,
        boots,
        shoes,
        boots,
        shuttles,
        high_heeled_shoes,
        ballerina,
        sports_shoes,
        vegan_footwear,
        on_a_wide_foot',
];
